### ISSUE TITLE
#include <vector> in utils.h

### ISSUE THREAD

**Issue by tleger1958** [mtux/GenealogicalTree#1]
Hello,
I had a problem with the compilation. I got the error : "error: ‘vector’ in namespace ‘std’ does not name a template type" in the file "utils.h".

I solved the issue by adding the header `#include <vector>` in "utils.h".

I hope it will help you.

**Comment by mtux** [comment]
Hi Thomas,

Thanks for your message, but I'm wondering why would someone compile that
code? What use does it have?
I've done it for some test, a year or so ago.

Cheers,
Mehrdad

**Comment by tleger1958** [comment]
Hi Mehrdad,

To get an executable, you must compile the code. And I just wanted to mean that at the compilation I had gotten an error, which I solved as well.

Or maybe I'm mistaken about the term "compilation"?

Cheers

**Comment by mtux** [comment]
Sure, to get an executable, but my question was why would someone want to run this code? I mean it doesn't solve any real world problem! does it?
It's just out of curiosity. ;)

And btw, as far as I know, it used to compile as it is last year that I wrote it. though based on what compiler or c++ version you ran, there might be issues.

**Comment by tleger1958** [comment]
I just wanted to test the program. Why would it be on Github if it is not to test?

I think there's a misunderstanding, is not it? ^^

**Comment by mtux** [comment]
yes maybe my question wasn't clear at first.
you're right, it's just very interesting for me to see someone would try to test it.

**Comment by tleger1958** [comment]
But yes I found the program was uninteresting. You have also right!
